#!/usr/bin/env node
// Packs src/Code.gs + Index/Styles/App.html into ONE file, dist/Code.gs, so
// the teacher pastes a single file into the Sheet's Apps Script editor. The
// HTML is embedded as strings and served through EMBEDDED_HTML (see doGet /
// include in Code.gs). Commit dist/Code.gs: it is what gets deployed.
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
require('child_process').execFileSync(process.execPath, [path.join(__dirname, 'build-rubrics.js')], { stdio: 'inherit' });
const code = read('src/Code.gs');
const html = { Index: read('src/Index.html'), Styles: read('src/Styles.html'), Rubrics: read('src/Rubrics.html'), App: read('src/App.html') };
// JSON.stringify gives a valid JS string literal; break "</script>" so the
// embedded App.html can never terminate a script tag if viewed as HTML.
const lit = s => JSON.stringify(s).replace(/<\/script>/g, '<\\/script>');
const out = code +
  '\n\n// =============================================================\n' +
  '// Embedded web-app files (generated by dev/build-single.js — do not edit here;\n' +
  '// edit src/*.html and rebuild).\n' +
  '// =============================================================\n' +
  'EMBEDDED_HTML = {\n' +
  '  Index: ' + lit(html.Index) + ',\n' +
  '  Styles: ' + lit(html.Styles) + ',\n' +
  '  Rubrics: ' + lit(html.Rubrics) + ',\n' +
  '  App: ' + lit(html.App) + '\n' +
  '};\n';
fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
fs.writeFileSync(path.join(root, 'dist/Code.gs'), out);
console.log('Wrote dist/Code.gs', `(${(out.length / 1024).toFixed(0)} KB, ${out.split('\n').length} lines)`);
