#!/usr/bin/env node
// Generates src/Rubrics.html from docs/G8_PE_Rubric_Bank.md so the app never
// hand-copies rubric wording. v1 needs the nine fundamental-skill ladders.
// Run: node dev/build-rubrics.js   (also run by build-preview / build-single)
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const md = fs.readFileSync(path.join(root, 'docs/G8_PE_Rubric_Bank.md'), 'utf8');

const KEYS = { 'Throw': 'throw', 'Catch': 'catch', 'Strike': 'strike', 'Dribble': 'dribble', 'Kick': 'kick', 'Balance': 'balance', 'Agility': 'agility', 'Jump & land': 'jump', 'Core stability': 'core' };
const ladders = {};
const sec = md.split('## Fundamental Skills')[1].split('\n## ')[0];
sec.split('\n').forEach(line => {
  const m = line.match(/^\|\s*\*\*(.+?)\*\*\s*\|(.+)\|\s*$/);
  if (!m) return;
  const name = m[1].trim(), key = KEYS[name];
  if (!key) throw new Error('Unknown skill in rubric bank: ' + name);
  const levels = m[2].split('|').map(s => s.trim()).filter(Boolean);
  if (levels.length !== 4) throw new Error(name + ': expected 4 levels, got ' + levels.length);
  ladders[key] = { name, levels };
});
if (Object.keys(ladders).length !== 9) throw new Error('Expected 9 ladders, got ' + Object.keys(ladders).length);

const out = '<script>\n// GENERATED by dev/build-rubrics.js from docs/G8_PE_Rubric_Bank.md — do not edit.\n' +
  'window.RUBRICS = ' + JSON.stringify({ ladders }, null, 1).replace(/<\/script>/g, '<\\/script>') + ';\n</script>\n';
fs.writeFileSync(path.join(root, 'src/Rubrics.html'), out);
console.log('Wrote src/Rubrics.html', Object.keys(ladders).join(', '));
